# Generated by Django 4.2.4 on 2023-08-09 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('shou-biz', 'Шоу-Биз'), ('proisshestviia', 'Происшествия'), ('novosti-sporta-kazakhstana', 'Новости спорта Казахстана'), ('politika', 'Политика'), ('ekonomika', 'Экономика'), ('obshchestvo', 'Общество'), ('v-mire', 'В мире')], max_length=30)),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 8, 9, 22, 19, 16, 25334))),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=5000)),
            ],
        ),
    ]
