# Generated by Django 4.2.4 on 2023-08-10 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 10, 23, 50, 58, 519926), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, help_text='Выберите директорию изображения', upload_to='media/img/', verbose_name='Картинка'),
        ),
    ]
