# Generated by Django 4.2.4 on 2023-08-11 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_date_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 11, 11, 43, 5, 313518), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, help_text='Выберите директорию изображения', upload_to='img/', verbose_name='Картинка'),
        ),
    ]
